apiVersion: ENC[AES256_GCM,data:MgM=,iv:EFpPyYdHVzz3tK/qLYdIpA5YFrEVpKjC5/JxLFyh6M8=,tag:WC68xfXVEcLq3ZWEDs+RnQ==,type:str]
kind: ENC[AES256_GCM,data:oHHyNMso,iv:R0bkzQFGkW1+kXKbEEwQ6kHZRVJ9UiM/dGnEVE2vvJs=,tag:qz0XkK9ML588zyialftW/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:G/GmsfcVHiE=,iv:PIn7rq7YDrE4BW+8kLD+Fl86sIldszVUd632noIyVEk=,tag:2PDp6uhMTP9Zg335goa7Gw==,type:str]
stringData:
    keys.txt: ENC[AES256_GCM,data:ZR4qDIEMarV1GJcbRFVrTyKWjX/1X0ztTsdSKjnGafFcRVEhCFekg+hRGjxAYOjB6PcLnfsO4NZZ+36WruW6Bru1NvSO+wu9avDHa8FOKwIbqP2ur0FC+4vrrkujEtiJDDSqYU9kqBMHX5DEHNUjDObxFDTNnlyRyzsuOmp84AyS+noh0n6DzmBkf3WhkyzS2C3aOLvyMjTJpT4inOfbOduiHP5ihA3gHGrETOtiO9icQ/HuMLL9Dp9C1hg=,iv:pi1hbhNYjrinImAUHEOA9JRFetD4cEr/QOL2+mKQ/Eg=,tag:Pw8dYZPHqFyVjfxB5r1sfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10mwuj608zt293dnk00tj6q6ypfl6phx3chfz7jxc3hk570pmg9es0g2rr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTU5KUHRyb2RGRGJHd255
            a01QSHZmMkZPK1d1SmMxVkh3NE9IUG53WUVJCmh6WnhpMFNFNXdlNmRsREhid1pL
            VlZ1d1NaNlY3RmFtSjBLank5cTZXRlEKLS0tIEZ1SzJrSHNmbm1pc3pWNW01NXJP
            WmFqbVVkOXRMdE8vK2c0Vm53VjhkeTQKSzOoA99umectD1BacYD6meseSqsmGgHU
            71mX1NrVKQBV7zBft8yxPEQp3pQeRtPyFfeXRvwJCywyh/GnUyyQSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:24:06Z"
    mac: ENC[AES256_GCM,data:Hn7OU+eR1jRR8VyqK8YOatgqddBPoE/FjOGYlmlQxcyvcKjhvYhvZ+gVeaAmeaF4IeqF2uLP9TiAQNBvF0hlHYR+EtI0h26W7Cdye1FskOdkd63h/4y1wcYw+36PviLwHGSkVYLAG9kDEt8Kn25kiKs4XRlcgURR6WuHKI5rsGo=,iv:GzaFBeJc4O3yFYax3EaxXhT/Ry/c0Rc5NlWYX4NdfW4=,tag:AFxH+Uoe2OZ1ltOzIodDwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
