configs:
    repositories:
        private-helm-repo:
            url: ENC[AES256_GCM,data:7XlTVlNqdCE3qERIOKQ/nepBZ8PhI3JmBMz+qOjShFM20mgwp7dGV621FMI9xH8=,iv:meIJD6jQY7NmaEmsQxnc5Dihma5vVs5zfs1dbaHbQTI=,tag:deKZChcE/8qCO4D1PqF7gw==,type:str]
            name: ENC[AES256_GCM,data:CQeum/HJF68abmMtUCQSHA==,iv:/ckWHYN6VuFhJzjc8w3bmxS6U2SgrbetekiR3rmgwMQ=,tag:OW4Dh95+tPtoO/tHa0ytTQ==,type:str]
            username: ENC[AES256_GCM,data:hs5w/Z3d4w==,iv:df13qgGWWLhnGva0sQEMJZPbiIjWRmx8CYFQs7wtf6c=,tag:F9vD9wXIgEL392ZvO19UKQ==,type:str]
            password: ENC[AES256_GCM,data:ic0QzEBS6PCmVFKk7hPja+3uyQLPir4GkMdamFR2lp+YyMRUTzfdHKUns4KdMVQQE0DIWmvG+tZhVVYTQJ19Uhc+JYQGCYyVpOTmn4Oz+TnPLCulazHiHrzJH3qI,iv:OfI2+KsxuylZnKsf0w2Czbl9DGyjkpFGj41UOG6s2zI=,tag:VfLLLHJ9gd4yBooGGvgavw==,type:str]
server:
    ingress:
        enabled: ENC[AES256_GCM,data:uSOdpQ==,iv:9HNJc019P5QWbM1MSchJdzVTWJzJpk7sZMrPyXOSJfM=,tag:56BTA/ELTpysERRzd7zdcw==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:1hSrcNn3OVcJQwD3C2xdfA==,iv:+n0qS2yndPoEykt4VHKxhLcQnkDhSbK9wVmQtPjOcGY=,tag:ldyULzSI3xMdGCCIZoPJrA==,type:str]
            nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:j5c/F0Y=,iv:wUjALkMf9GMmO1x95/5tcaOHidYOpk2+TPB9Ts+m9pM=,tag:PL3O5ncSx5tTKRvGlUA7OQ==,type:str]
        ingressClassName: ENC[AES256_GCM,data:7jK67IE=,iv:xcnvR+kEv92Sd0Wv9/qcwl73jNpOhncD0qsbdubvbt8=,tag:00AA9JWdmKAtK9x/bQwsfw==,type:str]
        hosts:
            - ENC[AES256_GCM,data:1JKEYh2VTMm8JalHct+tlBFJ/yY=,iv:KPH5B/nNPGGPpdc4MBYzfleNgjTHIF1cWQyhmxxxKLw=,tag:1/LQb6RJw1SqTfn/dBcgYA==,type:str]
        paths:
            - ENC[AES256_GCM,data:+g==,iv:DTk95YSUJ3vA/GP6WQJmXtpDaLhQ/v+4hfNx5eV1ySc=,tag:JEqNwxc9Ri86V7soJ/HBpw==,type:str]
        pathType: ENC[AES256_GCM,data:BKTa5MRL,iv:/zcF+i3+tfpXte1dQ2/DjEuSMk/GrJ93cKBjZ//viEc=,tag:fUtxttZT3NoI1e1s89vLBA==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:rz6jq3NFUldWL8l7R9c=,iv:0Syd1Y0lsW9cjjllb9vKj92yCeWJPGgeHAk/ylMzvnY=,tag:MkxPMERBzGVt459j2itBCg==,type:str]
              hosts:
                - ENC[AES256_GCM,data:001i+FzQ9iBkf6aHwnGyTyfaymA=,iv:fbNjVDEjE4MMdwFzB+cX9fqibC9G9ny2/9yt5uro2Rw=,tag:488vhQOGHFJ7dvzJl4glPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10mwuj608zt293dnk00tj6q6ypfl6phx3chfz7jxc3hk570pmg9es0g2rr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K1FRaDVaQ2Q2cC9rOUlv
            SEpHcElUbVpRcGh6KytsRHNhRzJEY29sWG1RClNSR05jellPTG5kNWhXQkRhU2hF
            aUxoYzdYTHcxNDA5SGhmMUZNOFg1TlEKLS0tIHBxQUpYMmNwVkh3endJQy9lSis3
            dko3eWZsTkR2U0dERnliVlVDbzJaeTQKrmqRIMeLS3r4kHPgw7BWLJfVqfTVw+Rx
            ZALkmRqxNsK+Eb+y7aExVTRKGrON8SLhXoyg/BAckox5Dig2BK0CIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T22:36:01Z"
    mac: ENC[AES256_GCM,data:08C1MLsi5nR8Nk8jiAnQewWhlvAXxpsEehL4PGpl3k0TcVkdUclE85R+xYC6nj9AYJrebuB0OW0Har0NNE3aHOlZGYDsCHBmI9VNn7SnFWlzul428kL6eTuD5DAWmhZAru4XMiZ2uravd/qd065eEIHLNENcz2xqJFSUsgAy8Xc=,iv:mHe3gZTfMhsKBuIVN4ByHGbaSnDnzZSsXnKFOu9QXL0=,tag:yyb4efMGsooACnw59s/g9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
